Update SMTP and API auth key in secrets; modify install-edc.yaml

diff --git a/charts/umbrella/templates/umbrella-secret.yaml b/charts/umbrella/templates/umbrella-secret.yaml
--- a/charts/umbrella/templates/umbrella-secret.yaml
+++ b/charts/umbrella/templates/umbrella-secret.yaml
@@ -279,6 +279,8 @@ spec:
               value: '{{ index .Values "tx-data-provider" "enabled" }}'
             - name: DATAPROVIDER_NAME
               value: '{{ index .Values "tx-data-provider" "tractusx-connector" "postgresql" "nameOverride" }}'
+            - name: EDC_PROVIDER_API_KEY
+              value: '{{ .Values.secretEnv.EDC_PROVIDER_API_KEY }}'
 
               ##### dataconsumer-1
             - name: DATACONSUMER1_PASSWORD
@@ -287,6 +289,8 @@ spec:
               value: "{{ .Values.dataconsumerOne.enabled }}"
             - name: DATACONSUMER1_NAME
               value: '{{ index .Values "dataconsumerOne" "tractusx-connector" "postgresql" "nameOverride" }}'
+            - name: EDC_CONSUMER1_API_KEY
+              value: '{{ .Values.secretEnv.EDC_CONSUMER1_API_KEY }}'
 
               ##### dataconsumer-2
             - name: DATACONSUMER2_PASSWORD
@@ -295,12 +299,22 @@ spec:
               value: "{{ .Values.dataconsumerTwo.enabled }}"
             - name: DATACONSUMER2_NAME
               value: '{{ index .Values "dataconsumerTwo" "tractusx-connector" "postgresql" "nameOverride" }}'
+            - name: EDC_CONSUMER2_API_KEY
+              value: '{{ .Values.secretEnv.EDC_CONSUMER2_API_KEY }}'
 
               #### dataprovider-dtr
             - name: DATAPROVIDER_DTR_PASSWORD
               value: "{{ .Values.secretEnv.DATAPROVIDER_DTR_PASSWORD }}"
             - name: DATAPROVIDER_DTR_NAME
               value: "dataprovider-secret-dtr-postgres-init"
+
+              #### bdrs-server-memory:
+            - name: BDRS_SEVER_Memory
+              value: '{{ index .Values "bdrs-server-memory" "enabled" }}'
+            - name: BDRS_SEVER_Memory_Name
+              value: '{{ index .Values "bdrs-server-memory" "nameOverride" }}'
+            - name:   BDRS_API_AUTH_KEY
+              value: '{{ .Values.secretEnv.BDRS_API_AUTH_KEY }}'
 
           command:
             - /bin/sh
@@ -416,7 +430,6 @@ spec:
                 echo "Checking/creating {{ .Release.Name }}-sharedidp-master-realm-seeding secret..."
                 if kubectl get secret {{ .Release.Name }}-sharedidp-master-realm-seeding -n "$NAMESPACE" >/dev/null 2>&1; then
                   kubectl patch secret {{ .Release.Name }}-sharedidp-master-realm-seeding -n "$NAMESPACE" \
-                    --type merge \
                     -p "{\"stringData\":{\"sa-cx-operator\":\"$SA_CX_OPERATOR\",\"sa-provisioning\":\"$SA_PROVISIONING\"}}"
                   echo "{{ .Release.Name }}-sharedidp-master-realm-seeding Secret updated."
                 else
@@ -447,7 +460,7 @@ spec:
               else
                 echo "centralidp.enabled is false, skipping centralidp secret."
               fi
-
+              
               #############################################################################
               ##### centralidp-postgresql
               if [ "$CENTRALIDP_PG_ENABLED" = "true" ]; then
@@ -502,7 +515,6 @@ spec:
                 if kubectl get secret {{ .Release.Name }}-centralidp-base-service-accounts -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   echo "Secret exists. Patching values..."
                   kubectl patch secret {{ .Release.Name }}-centralidp-base-service-accounts -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{
                           \"sa-cl1-reg-2\":\"$SA_CL1_REG_2\",
                           \"sa-cl2-01\":\"$SA_CLI2_01\",
@@ -614,6 +626,7 @@ spec:
               else
                 echo "centralidp.enabled is false, skipping extra service account secrets."
               fi
+
               #############################################################################
               ##### bpdm-postgres
               ###### --- Script to bpdm-postgres --- ######
@@ -732,7 +745,6 @@ spec:
                 echo "bpndiscovery.enabled or bpndiscovery.enablePostgres is false, skipping secret update."
               fi
 
-
               #############################################################################
               ##### portal-backend-interfaces
               ###### --- Script to portal-backend-interfaces --- ######
@@ -772,7 +784,6 @@ spec:
                 echo "Checking/creating {{ .Release.Name }}-$BPNDISCOVERY_NAME secret..."
                 if kubectl get secret {{ .Release.Name }}-$BPNDISCOVERY_NAME -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   kubectl patch secret {{ .Release.Name }}-$BPNDISCOVERY_NAME -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{
                           \"SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCOVERYFINDER_CLIENT_AUTHORIZATION_GRANT_TYPE\":\"$AUTHORIZATION_GRANT_TYPE\"
                         }}"
@@ -795,7 +806,6 @@ spec:
                 # Create or patch portal-client-secret
                 if kubectl get secret {{ .Release.Name }}-$SSI_CREDENTIAL_ISSUER_NAME -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   kubectl patch secret {{ .Release.Name }}-$SSI_CREDENTIAL_ISSUER_NAME -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{\"portal-client-secret\":\"$PORTAL_CLIENT_SECRET\"}}"
                   echo "Portal client secret updated."
                 else
@@ -808,7 +818,6 @@ spec:
                 # Create or patch wallet-client-secret
                 if kubectl get secret {{ .Release.Name }}-$SSI_CREDENTIAL_ISSUER_NAME -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   kubectl patch secret {{ .Release.Name }}-$SSI_CREDENTIAL_ISSUER_NAME -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{\"wallet-client-secret\":\"$WALLET_CLIENT_SECRET\"}}"
                   echo "Wallet client secret updated."
                 else
@@ -829,7 +838,6 @@ spec:
 
                 if kubectl get secret ssi-dim-wallet-secret -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   kubectl patch secret ssi-dim-wallet-secret -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{
                           \"PORTAL_CLIENT_SECRET\":\"$SSI_PORTAL_CLIENT_SECRET\"
                         }}"
@@ -852,7 +860,6 @@ spec:
                 if kubectl get secret portal-backend-keycloak -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   echo "Secret exists. Patching values..."
                   kubectl patch secret portal-backend-keycloak -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{
                           \"central-client-secret\":\"$SAME_SA_CL1_REG_2\",
                           \"shared-client-secret\":\"$SA_CL1_REG_1\"
@@ -878,7 +885,6 @@ spec:
                 if kubectl get secret {{ .Release.Name }}-$ISSUER_POSTGRES_NAME -n {{ .Release.Namespace }} >/dev/null 2>&1; then
                   echo "Secret exists. Patching values..."
                   kubectl patch secret {{ .Release.Name }}-$ISSUER_POSTGRES_NAME -n {{ .Release.Namespace }} \
-                    --type merge \
                     -p "{\"stringData\":{
                           \"postgres-password\":\"$UMBRELLA_ISSUER_POSTGRES_PASSWORD\",
                           \"password\":\"$UMBRELLA_ISSUER_POSTGRES_PASSWORD\",
@@ -922,6 +928,7 @@ spec:
                 echo "Patching Controlplane Deployment..."
                 kubectl set env deployment {{ .Release.Name }}-dataprovider-edc-controlplane \
                   EDC_DATASOURCE_DEFAULT_PASSWORD="$PASSWORD_DATAPROVIDER" \
+                  EDC_API_AUTH_KEY="$EDC_PROVIDER_API_KEY" \
                   -n {{ .Release.Namespace }}
 
                 #### --- Patch Dataplane Deployment --- ####
@@ -980,6 +987,7 @@ spec:
                 # Patch Controlplane Deployment env variable
                 kubectl set env deployment {{ .Release.Name }}-dataconsumer-edc-controlplane \
                   EDC_DATASOURCE_DEFAULT_PASSWORD="$DATACONSUMER1_PASSWORD" \
+                  EDC_API_AUTH_KEY="$EDC_CONSUMER1_API_KEY" \
                   -n {{ .Release.Namespace }}
 
                 # Patch Dataplane Deployment env variable
@@ -1015,10 +1023,28 @@ spec:
                     --from-literal=postgres-password="$PASSWORD_DATACONSUMER2"
                   echo "{{ .Release.Name }}-$DATACONSUMER2_NAME created successfully."
                 fi
+
+                # Patch Controlplane Deployment env variables
+                kubectl set env deployment {{ .Release.Name }}-dataconsumer-edc-controlplane \
+                  EDC_DATASOURCE_DEFAULT_PASSWORD="$PASSWORD_DATACONSUMER2" \
+                  EDC_API_AUTH_KEY="$EDC_CONSUMER2_API_KEY" \
+                  -n {{ .Release.Namespace }} || echo "Failed to patch controlplane deployment."
+
+                # Patch Dataplane Deployment env variable
+                kubectl set env deployment {{ .Release.Name }}-dataconsumer-edc-dataplane \
+                  EDC_DATASOURCE_DEFAULT_PASSWORD="$PASSWORD_DATACONSUMER2" \
+                  -n {{ .Release.Namespace }} || echo "Failed to patch dataplane deployment."
+
+                # Restart both Deployments
+                kubectl rollout restart deployment {{ .Release.Name }}-dataconsumer-edc-controlplane -n {{ .Release.Namespace }}
+                kubectl rollout restart deployment {{ .Release.Name }}-dataconsumer-edc-dataplane -n {{ .Release.Namespace }}
+
+                echo "dataconsumerTwo deployments restarted successfully."
+
               else
                 echo "dataconsumerTwo.enabled is false, skipping $DATACONSUMER2_NAME secret creation."
               fi
-              
+
               #############################################################################
               ##### dataprovider-dtr
               ###### --- Script to create or update dataprovider-secret-dtr-postgres-init --- ######
@@ -1053,4 +1079,23 @@ spec:
               fi   
                               
               #############################################################################
+              ###### --- Script to update bdrs-server-memory deployment --- ######
+              if [ "$BDRS_SEVER_Memory" = "true" ]; then
+                echo "bdrs-server-memory is enabled. Patching $BDRS_SEVER_Memory_Name deployment..."
+
+                # Patch Deployment environment variable
+                kubectl set env deployment "$BDRS_SEVER_Memory_Name" \
+                  EDC_API_AUTH_KEY="$BDRS_API_AUTH_KEY" \
+                  -n {{ .Release.Namespace }} || echo "Failed to patch $BDRS_SEVER_Memory_Name deployment."
+
+                # Restart Deployment
+                kubectl rollout restart deployment "$BDRS_SEVER_Memory_Name" -n {{ .Release.Namespace }}
+
+                echo "$BDRS_SEVER_Memory_Name deployment restarted successfully."
+
+              else
+                echo "bdrs-server-memory.enabled is false, skipping $BDRS_SEVER_Memory_Name deployment update."
+              fi
+
+
 {{- end }}
